[package]
name = "kali-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = "0.4"
clap = { version = "4", features = ["derive"] }
rustyline = "14"

tracing = { workspace = true }
tracing-subscriber = { workspace = true }
