[workspace]
resolver = "2"
members = ["./crates/*", "crates/kali-ast2", "crates/kali-parse2"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
