[workspace]
resolver = "2"
members = ["./crates/*", "crates/kali-ast3", "crates/kali-lalrpop", "crates/kali-parse3"]

[workspace.dependencies]
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
